<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGf3zqFs\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGf3zqFs/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerGf3zqFs.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerGf3zqFs\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerGf3zqFs\appAppKernelProdContainer([
    'container.build_hash' => 'Gf3zqFs',
    'container.build_id' => 'f9bc2b99',
    'container.build_time' => 1712199446,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGf3zqFs');
